// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Bang.Tests.Features.GameRules
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TourDunJoueurFeature : object, Xunit.IClassFixture<TourDunJoueurFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PlayerRound.feature"
#line hidden
        
        public TourDunJoueurFeature(TourDunJoueurFeature.FixtureData fixtureData, Bang_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr-FR"), "Features/GameRules", "Tour d\'un joueur", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "playerName",
                        "characterName",
                        "role"});
            table6.AddRow(new string[] {
                        "Jean",
                        "Bart Cassidy",
                        "Schérif"});
            table6.AddRow(new string[] {
                        "Max",
                        "Rose Doolan",
                        "Renégat"});
            table6.AddRow(new string[] {
                        "Emilie",
                        "Willy le Kid",
                        "Hors-la-loi"});
            table6.AddRow(new string[] {
                        "Martin",
                        "Sam le Vautour",
                        "Hors-la-loi"});
#line 5
 testRunner.Given("une partie est initiée par ces joueurs", ((string)(null)), table6, "Sachant qu\'");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "playerName"});
            table7.AddRow(new string[] {
                        "Jean"});
            table7.AddRow(new string[] {
                        "Max"});
            table7.AddRow(new string[] {
                        "Emilie"});
            table7.AddRow(new string[] {
                        "Martin"});
#line 11
 testRunner.And("les joueurs rejoignent la partie", ((string)(null)), table7, "Et que ");
#line hidden
#line 17
 testRunner.When("c\'est au tour de \"Jean\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Piocher 2 cartes")]
        [Xunit.TraitAttribute("FeatureTitle", "Tour d\'un joueur")]
        [Xunit.TraitAttribute("Description", "Piocher 2 cartes")]
        public void Piocher2Cartes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Piocher 2 cartes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 20
 testRunner.Then("\"Jean\" possède 7 cartes en main", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Jouer une carte de type Arme")]
        [Xunit.TraitAttribute("FeatureTitle", "Tour d\'un joueur")]
        [Xunit.TraitAttribute("Description", "Jouer une carte de type Arme")]
        [Xunit.InlineDataAttribute("Volcanic", "1", new string[0])]
        [Xunit.InlineDataAttribute("Schofield", "2", new string[0])]
        [Xunit.InlineDataAttribute("Remington", "3", new string[0])]
        [Xunit.InlineDataAttribute("Carabine", "4", new string[0])]
        [Xunit.InlineDataAttribute("Winchester", "5", new string[0])]
        public void JouerUneCarteDeTypeArme(string weaponName, string range, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("weaponName", weaponName);
            argumentsOfScenario.Add("range", range);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Jouer une carte de type Arme", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 23
 testRunner.Given(string.Format("\"Jean\" possède une carte \"{0}\" dans son jeu", weaponName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Etant donné que ");
#line hidden
#line 24
 testRunner.When(string.Format("\"Jean\" joue une carte \"{0}\"", weaponName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
#line 25
 testRunner.Then(string.Format("\"Jean\" place sa carte \"{0}\" devant lui", weaponName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 26
 testRunner.And(string.Format("\"Jean\" est armé d\'une \"{0}\" ayant une portée de {1}", weaponName, range), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
#line 27
 testRunner.And("\"Jean\" possède 6 cartes en main", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TourDunJoueurFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TourDunJoueurFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
