// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Pang.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class InitialisationDuJeuFeature : object, Xunit.IClassFixture<InitialisationDuJeuFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GameCreation.feature"
#line hidden
        
        public InitialisationDuJeuFeature(InitialisationDuJeuFeature.FixtureData fixtureData, Pang_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr-FR"), "Features", "Initialisation du jeu", @"![Calculator](https://specflow.org/wp-content/uploads/2020/09/calculator.png)
Simple calculator for adding **two** numbers

Link to a feature: [Calculator](Pang.Tests/Features/Calculator.feature)
***Further read***: **[Learn more about how to generate Living Documentation](https://docs.specflow.org/projects/specflow-livingdoc/en/latest/LivingDocGenerator/Generating-Documentation.html)**", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Démarrer la partie à 4 joueurs")]
        [Xunit.TraitAttribute("FeatureTitle", "Initialisation du jeu")]
        [Xunit.TraitAttribute("Description", "Démarrer la partie à 4 joueurs")]
        public virtual void DemarrerLaPartieA4Joueurs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Démarrer la partie à 4 joueurs", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "playerName"});
                table1.AddRow(new string[] {
                            "Jean"});
                table1.AddRow(new string[] {
                            "Max"});
                table1.AddRow(new string[] {
                            "Emilie"});
                table1.AddRow(new string[] {
                            "Martin"});
#line 9
 testRunner.Given("ces joueurs veulent lancer une partie", ((string)(null)), table1, "Sachant que ");
#line hidden
#line 15
 testRunner.When("la partie s\'initialise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "roleName",
                            "count"});
                table2.AddRow(new string[] {
                            "Sheriff",
                            "1"});
                table2.AddRow(new string[] {
                            "Renegade",
                            "1"});
                table2.AddRow(new string[] {
                            "Outlaw",
                            "2"});
#line 16
 testRunner.Then("la composition des rôles est la suivante", ((string)(null)), table2, "Alors ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Démarrer la partie à 5 joueurs")]
        [Xunit.TraitAttribute("FeatureTitle", "Initialisation du jeu")]
        [Xunit.TraitAttribute("Description", "Démarrer la partie à 5 joueurs")]
        public virtual void DemarrerLaPartieA5Joueurs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Démarrer la partie à 5 joueurs", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "playerName"});
                table3.AddRow(new string[] {
                            "Jean"});
                table3.AddRow(new string[] {
                            "Max"});
                table3.AddRow(new string[] {
                            "Emilie"});
                table3.AddRow(new string[] {
                            "Martin"});
                table3.AddRow(new string[] {
                            "Anna"});
#line 23
 testRunner.Given("ces joueurs veulent lancer une partie", ((string)(null)), table3, "Sachant que ");
#line hidden
#line 30
 testRunner.When("la partie s\'initialise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "roleName",
                            "count"});
                table4.AddRow(new string[] {
                            "Sheriff",
                            "1"});
                table4.AddRow(new string[] {
                            "Renegade",
                            "1"});
                table4.AddRow(new string[] {
                            "Outlaw",
                            "2"});
                table4.AddRow(new string[] {
                            "Assistant",
                            "1"});
#line 31
 testRunner.Then("la composition des rôles est la suivante", ((string)(null)), table4, "Alors ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Démarrer la partie à 6 joueurs")]
        [Xunit.TraitAttribute("FeatureTitle", "Initialisation du jeu")]
        [Xunit.TraitAttribute("Description", "Démarrer la partie à 6 joueurs")]
        public virtual void DemarrerLaPartieA6Joueurs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Démarrer la partie à 6 joueurs", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 38
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "playerName"});
                table5.AddRow(new string[] {
                            "Jean"});
                table5.AddRow(new string[] {
                            "Max"});
                table5.AddRow(new string[] {
                            "Emilie"});
                table5.AddRow(new string[] {
                            "Martin"});
                table5.AddRow(new string[] {
                            "Anna"});
                table5.AddRow(new string[] {
                            "Eric"});
#line 39
 testRunner.Given("ces joueurs veulent lancer une partie", ((string)(null)), table5, "Sachant que ");
#line hidden
#line 47
 testRunner.When("la partie s\'initialise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "roleName",
                            "count"});
                table6.AddRow(new string[] {
                            "Sheriff",
                            "1"});
                table6.AddRow(new string[] {
                            "Renegade",
                            "1"});
                table6.AddRow(new string[] {
                            "Outlaw",
                            "3"});
                table6.AddRow(new string[] {
                            "Assistant",
                            "1"});
#line 48
 testRunner.Then("la composition des rôles est la suivante", ((string)(null)), table6, "Alors ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Démarrer la partie à 7 joueurs")]
        [Xunit.TraitAttribute("FeatureTitle", "Initialisation du jeu")]
        [Xunit.TraitAttribute("Description", "Démarrer la partie à 7 joueurs")]
        public virtual void DemarrerLaPartieA7Joueurs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Démarrer la partie à 7 joueurs", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "playerName"});
                table7.AddRow(new string[] {
                            "Jean"});
                table7.AddRow(new string[] {
                            "Max"});
                table7.AddRow(new string[] {
                            "Emilie"});
                table7.AddRow(new string[] {
                            "Martin"});
                table7.AddRow(new string[] {
                            "Anna"});
                table7.AddRow(new string[] {
                            "Eric"});
                table7.AddRow(new string[] {
                            "Jane"});
#line 56
 testRunner.Given("ces joueurs veulent lancer une partie", ((string)(null)), table7, "Sachant que ");
#line hidden
#line 65
 testRunner.When("la partie s\'initialise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "roleName",
                            "count"});
                table8.AddRow(new string[] {
                            "Sheriff",
                            "1"});
                table8.AddRow(new string[] {
                            "Renegade",
                            "1"});
                table8.AddRow(new string[] {
                            "Outlaw",
                            "3"});
                table8.AddRow(new string[] {
                            "Assistant",
                            "2"});
#line 66
 testRunner.Then("la composition des rôles est la suivante", ((string)(null)), table8, "Alors ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                InitialisationDuJeuFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                InitialisationDuJeuFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
